CREATE TABLE IF NOT EXISTS order_item
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
    restaurant_menu_item_id BIGINT REFERENCES restaurant_menu_item(id) ON DELETE CASCADE NOT NULL,
    price INT NOT NULL CHECK (price>=10),
    quantity INT NOT NULL CHECK (quantity>0)
);